sudo: required
services:
    - docker
before_install:
    - docker build -t bogdangherla2/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bogdangherla2/react-test npm test -- --coverage
after_succes:
    - docker build -t bogdangherla2/multi-client ./client
    - docker build -t bogdangherla2/multi-nginx ./nginx    
    - docker build -t bogdangherla2/multi-server ./server   
    - docker build -t bogdangherla2/multi-worker ./worker  
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push bogdangherla2/multi-client     
    - docker push bogdangherla2/multi-nginx 
    - docker push bogdangherla2/multi-server 
    - docker push bogdangherla2/multi-worker 
    